general.import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
size = 14
normal = { family = 'JetbrainsMono Nerd Font' }

[env]
TERM = "xterm-256color"

[window]
decorations_theme_variant = "Dark"
startup_mode = "Maximized"

[terminal]
shell = { program = "zellij", args = ["-l", "welcome"] }

[keyboard]
bindings = [
  { key = "T", mods = "Command", action = "None" }
]
